### ISSUE TITLE
Dashboards "further info" section links #3 and #4 clashes with content policy (and the Diva link)

### ISSUE THREAD

**Issue by mskyttner** [KTH-Library/bibliomatrix#49]

**Comment by agnepagne** [comment]
The easiest fix is maybe to just upload the documents with the app. Where/how do we do that?

**Comment by mskyttner** [comment]
Documents can be put in the www directory of the shiny app, links are then short like `[link-desc](document.pdf)`. This should be the simplest solution and work well esp if the documents are not too big.

**Comment by agnepagne** [comment]
Documents are put in inst/shiny-apps/abm/www/ and links in abm.Rmd are updated in a new branch. Can't test properly because I can't get dashboard from API to work with the shiny app for some reason (worked last year...). Links from standalone dashboard fail (since dashboard knows nothing about the shiny app www directory) .

Document #1 is temporary and has to be replaced when the guide is final.

The #4 link, which is one of the two we have policy problems with, is a web page within the kth.se framework. I have not attempted to make a local web page out of this. Maybe we could use the DiVA manual instead. Kind of depends how likely it is that the deployed production app will have problems with kth.se content policy.

**Comment by agnepagne** [comment]
The reason that shiny/api combination did not work for me was that I started the repository version of the app instead of the package version (the app's www root is then the www directory in the repository while the app itself points at the package app's www directory for saving flexdashboards to disk). Links seem to work and point to the right files when app is started from package.

Can't recreate documentation because obsolete docs use bad database calls, therefore waiting with creating pull request for now. I guess we should also finish the guide before merging to master.

**Comment by mskyttner** [comment]
For the Diva link (shown to logged in users), I think adding to the link a `<a ..... target='_blank'>` (see https://stackoverflow.com/questions/4198788/is-it-alright-to-use-target-blank-in-html5) may work. It is not mentioned in this issues title, but maybe should have been.

I wonder if this would work for the number 4 link that @agnepagne mentioned, too.

**Comment by agnepagne** [comment]
Nice solution @mskyttner, if it works for the DiVA link there is no reason to belive it wouldn't work for link `#4` too.

**Comment by mskyttner** [comment]
I tested this by live-editing the HTML on the ref server, it seems to work (for me):

I did "inspect element" and "edit html" and added "_target='_blank'" and was then able to open the Diva links:

![image](https://user-images.githubusercontent.com/1715840/72451948-06c2d580-37bd-11ea-9283-8dac65fb7cd1.png)

**Comment by agnepagne** [comment]
Great, @mskyttner!
Pull request coming up when we have updated the Guide.

**Comment by mskyttner** [comment]
DiVA links fixed in d6da9ce3675a725cc77a2d64f9429086ce0cf7c6
